# Numpy学习（一）

### 1. 创建数组
**1.1 通过列表或者元组创建**

In [1]:
import numpy as np

a = [1, 2, 3, 4]
b = (1, 2, 3, 4)
na = np.array(a, dtype=np.float32)
nb = np.array(b, dtype=np.float32)
a, nb, na, type(na), type(nb)

([1, 2, 3, 4],
 array([1., 2., 3., 4.], dtype=float32),
 array([1., 2., 3., 4.], dtype=float32),
 numpy.ndarray,
 numpy.ndarray)

**1.2 指定范围创建**

In [2]:
nc = np.arange(1, 6, dtype=np.float32)
nd = np.arange(7, dtype=np.float32)
nc, nd

(array([1., 2., 3., 4., 5.], dtype=float32),
 array([0., 1., 2., 3., 4., 5., 6.], dtype=float32))

**1.3 创建特定元素的数组**

In [3]:
# 创建全0元素和全1元素数组
ne = np.ones((3, 3), dtype=np.int8)
nf = np.zeros((3, 3), dtype=np.int8)
ne, nf

(array([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=int8),
 array([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=int8))

### 2. numpy索引与切片
numpy各个维度的下标都是从0开始的，根据下标访问指定位置的元素。

**2.1 访问单个元素**

In [4]:
ng = np.arange(16.).reshape((4, 4))
num = ng[2, 3]  # 访问指定位置的单个元素
ng, num

(array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]]),
 11.0)

**2.2 访问多个指定位置元素**

In [5]:
nums1 = ng[(0, 1, 2), (1, 2, 3)]
nums1

array([ 1.,  6., 11.])

**2.3 访问行或者列**

可以使用:访问连续的行和列

In [6]:
r1 = ng[0:2, :]  # 取出第一行和第二行
c1 = ng[:, 0:2]  # 取出第一列和第二列
r1, c1

(array([[0., 1., 2., 3.],
        [4., 5., 6., 7.]]),
 array([[ 0.,  1.],
        [ 4.,  5.],
        [ 8.,  9.],
        [12., 13.]]))

使用列表或者元组，访问指定的行或者列

In [7]:
r2 = ng[(0, 2), :]  # 访问第1行和第3行
c2 = ng[:, (0, 2)]  # 访问第1列和第3列
r2, c2

(array([[ 0.,  1.,  2.,  3.],
        [ 8.,  9., 10., 11.]]),
 array([[ 0.,  2.],
        [ 4.,  6.],
        [ 8., 10.],
        [12., 14.]]))

**2.4 访问多行和多列**

In [8]:
nh = np.arange(36.).reshape((6, 6))
nums2 = nh[1:3, 2:4]  # 取多行和多列
nh, nums2

(array([[ 0.,  1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10., 11.],
        [12., 13., 14., 15., 16., 17.],
        [18., 19., 20., 21., 22., 23.],
        [24., 25., 26., 27., 28., 29.],
        [30., 31., 32., 33., 34., 35.]]),
 array([[ 8.,  9.],
        [14., 15.]]))

### 3. 数组形状调整

数组形状调整可以通过reshape()来实现，并指定目标形状

In [11]:
nh.reshape((4, 9)), nh.reshape((-1, 4))    # -1表示该维度由代码自动推理出来

(array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12., 13., 14., 15., 16., 17.],
        [18., 19., 20., 21., 22., 23., 24., 25., 26.],
        [27., 28., 29., 30., 31., 32., 33., 34., 35.]]),
 array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.],
        [20., 21., 22., 23.],
        [24., 25., 26., 27.],
        [28., 29., 30., 31.],
        [32., 33., 34., 35.]]))

### 4. numpy数组拼接

数组拼接是将2个及以上的数组拼接成一个数组的操作，需要指定拼接的轴，即在哪一个维度上进行拼接。除了进行拼接的那个维度，其余维度必须相等，否则无法拼接

**4.1 使用np.concatenate()**

In [10]:
ni = np.arange(15.).reshape(3, 5)
nj = np.ones((3, 5))
nk = np.concatenate((ni, nj), axis=0)
nl = np.concatenate((ni, nj), axis=1)
ni, nj, nk, nl

(array([[ 0.,  1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.,  9.],
        [10., 11., 12., 13., 14.]]),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]),
 array([[ 0.,  1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.,  9.],
        [10., 11., 12., 13., 14.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.]]),
 array([[ 0.,  1.,  2.,  3.,  4.,  1.,  1.,  1.,  1.,  1.],
        [ 5.,  6.,  7.,  8.,  9.,  1.,  1.,  1.,  1.,  1.],
        [10., 11., 12., 13., 14.,  1.,  1.,  1.,  1.,  1.]]))